spring.application.name=RETO_Conciertos

server.port=8086


#LO COMENTADO ES SI FUERA SIN XAMPP
# para mysql 8 bbdd nombbdd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# para el my5 com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3310/conciertos?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
#para el my5 jdbc:mysql://localhost:3306/nombbdd?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
# no pass spring.datasource.password=xxxxxxxxx

spring.jpa.show-sql=true
# Hibernate 6+ detecta el dialecto solo, pero si quieres forzarlo:
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update